application: mc-quizzer
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10d"

handlers:
# show index.html for directories

- url: (.*/)
  static_files: html\1index.html
  upload: html(.*)index.html

# all other files
- url: /
  static_dir: html
